/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aec3_mp_javier_mora;

import java.awt.event.ActionEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Javi
 */
public class Calculadora extends javax.swing.JFrame {
    private static final long serialVersionUID = 1L; 
    

    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiquetaEntrad1 = new javax.swing.JTextField();
        textoSalida = new javax.swing.JTextField();
        botonCubo = new javax.swing.JButton();
        textoEntrada = new javax.swing.JLabel();
        textSalida = new javax.swing.JLabel();
        botonMCD = new javax.swing.JButton();
        botonDescomponer = new javax.swing.JButton();
        botonMCM = new javax.swing.JButton();
        botonCubo4 = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        etiquetaEntrada2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        textoEntrada1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoSalida.setEditable(false);
        textoSalida.setToolTipText("Campo no editable");
        textoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoSalidaActionPerformed(evt);
            }
        });

        botonCubo.setText("Elevar al cubo");
        botonCubo.setToolTipText("<html>\nEleva al cubo el valor introducido en<br>\nel campo \"Entrada 1\".<br>\n</html>");
        botonCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCuboActionPerformed(evt);
            }
        });

        textoEntrada.setText("Entrada 1:");

        textSalida.setText("Salida:");

        botonMCD.setText("MCD");
        botonMCD.setToolTipText("<html>\nCalcula el Máximo Cómun Divisor entre<br>\nlos valores introducidos en el campo<br>\n\"Entrada 1\" y \"Entrada 2\".<br>\n</html>");
        botonMCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMCDActionPerformed(evt);
            }
        });

        botonDescomponer.setText("Descomponer");
        botonDescomponer.setToolTipText("<html>\nDescompone el valor de \"Entrada 1\"<br>\nen sus divisores enteros.<br>\n</html>");
        botonDescomponer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDescomponerActionPerformed(evt);
            }
        });

        botonMCM.setText("MCM");
        botonMCM.setToolTipText("<html>\nCalcula el Mínimo Común Múltiplo de los<br>\nvalores introducidos en los campos<br>\n\"Entrada 1\" y \"Entrada 2\".<br>\n</html>");
        botonMCM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMCMActionPerformed(evt);
            }
        });

        botonCubo4.setText("Combinatorio");
        botonCubo4.setToolTipText("<html>\nCalcula el número combinatorio según los<br>\nvalores introducidos en los campos \"Entrada 1\" <br>\ny \"Entrada 2\".\n</html>");
        botonCubo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCubo4ActionPerformed(evt);
            }
        });

        botonBorrar.setText("Borrar");
        botonBorrar.setToolTipText("<html>\nBorra valores introducidos<br>\n</html>");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        textoEntrada1.setText("Entrada 2:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonCubo4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonCubo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonMCM, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonDescomponer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonMCD, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textoEntrada)
                                    .addComponent(textoEntrada1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiquetaEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(etiquetaEntrad1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textSalida)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEntrad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoEntrada)
                    .addComponent(textSalida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaEntrada2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoEntrada1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 13, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCubo)
                    .addComponent(botonDescomponer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMCM)
                    .addComponent(botonMCD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCubo4)
                    .addComponent(botonBorrar))
                .addContainerGap())
        );

        textoEntrada.getAccessibleContext().setAccessibleName("textoEntrada");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoSalidaActionPerformed
        
    }//GEN-LAST:event_textoSalidaActionPerformed

    private void botonCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuboActionPerformed
        
        registrarEscuchadores(evt);   
    }//GEN-LAST:event_botonCuboActionPerformed

    private void botonMCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMCDActionPerformed
        registrarEscuchadores(evt); 
    }//GEN-LAST:event_botonMCDActionPerformed

    private void botonDescomponerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDescomponerActionPerformed
        registrarEscuchadores(evt);
    }//GEN-LAST:event_botonDescomponerActionPerformed

    private void botonMCMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMCMActionPerformed
        registrarEscuchadores(evt);
    }//GEN-LAST:event_botonMCMActionPerformed

    private void botonCubo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCubo4ActionPerformed
        registrarEscuchadores(evt); 
    }//GEN-LAST:event_botonCubo4ActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        registrarEscuchadores(evt); 
    }//GEN-LAST:event_botonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }
    
    /** Escribe el número en el campo de texto de la salida **/
    public void escribirSalida(int num){ 
        textoSalida.setText(""+num);
    }
    
    /** Escribe el número en el campo de texto de la salida **/
    public void borraDatos(){ 
        textoSalida.setText("");
        etiquetaEntrad1.setText("");
        etiquetaEntrada2.setText("");
       
    }
    
     /** Escribe el número en el campo de texto de la salida **/
    public void escribirSalidaArray(ArrayList<Integer> arrayResuls){ 
           
        textoSalida.setText(arrayResuls.toString());
       
    }
    
    /** Este método registra los escuchadores de esta aplicación **/
    public void registrarEscuchadores(ActionEvent evt){
         Escuchador e = new Escuchador(this, evt);      
    }

    /**
     * Método que lee el primer campo, en caso de error (i.e un valor 
     * no númerico), salta la excepcición general Exception con un
     * mensaje de error.
     * @return 
     */
    public int leerEntrada1(){ 
        int num=0;
    
    try
    {
        Integer numInteger = Integer.valueOf(this.etiquetaEntrad1.getText());
        num = numInteger.intValue(); 
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,
        "El número entero de entrada del valor 1 es incorrecto.",
        "Error", JOptionPane.ERROR_MESSAGE);
    }
        return num;

    }
    
    /**
     * Método que lee el primer campo, en caso de error (i.e un valor 
     * no númerico), salta la excepcición general Exception con un
     * mensaje de error.
     * @return 
     */
    public int leerEntrada2(){ 
        int num=0;
    
    try
    {
        Integer numInteger = Integer.valueOf(this.etiquetaEntrada2.getText());
        num = numInteger.intValue(); 
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,
        "El número entero de entrada del valor 2 es incorrecto.",
        "Error", JOptionPane.ERROR_MESSAGE);
    }
        return num;

    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonCubo;
    private javax.swing.JButton botonCubo4;
    private javax.swing.JButton botonDescomponer;
    private javax.swing.JButton botonMCD;
    private javax.swing.JButton botonMCM;
    private javax.swing.JTextField etiquetaEntrad1;
    private javax.swing.JTextField etiquetaEntrada2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel textSalida;
    private javax.swing.JLabel textoEntrada;
    private javax.swing.JLabel textoEntrada1;
    private javax.swing.JTextField textoSalida;
    // End of variables declaration//GEN-END:variables
}
